version: '2'
services:
  hbase:
    build:
      context: hadoop-base
      args:
    image: nberserk/armhf-hadoop-base
  hslave:
    build: hadoop-slave
    image: nberserk/armhf-hadoop-slave
    depends_on:
      - hbase
  hmaster:
    build: hadoop-master
    image: nberserk/armhf-hadoop-master
    depends_on:
      - hbase
  sslave:
    build: spark-slave
    image: nberserk/armhf-spark-slave
    depends_on:
      - hslave
  smaster:
    build: spark-master
    image: nberserk/armhf-spark-master
    depends_on:
      - hmaster



